<%@ Page Title="Receiving History" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="UnloadCompareHistory.aspx.cs" Inherits="BabcoUnloadCompare.Web.UnloadCompareHistory" %>
<asp:Content ID="t" ContentPlaceHolderID="TitleContent" runat="server">Receiving History</asp:Content>
<asp:Content ID="m" ContentPlaceHolderID="MainContent" runat="server">
<section class="hero-row"><div><span class="eyebrow">RECEIVING</span><h1>Receiving History</h1><p>Find, reopen, verify, print or export prior unload comparisons.</p></div><a class="btn primary" href="UnloadCompare.aspx">+ New Receiving</a></section>
<section class="card filter-grid"><div class="field"><label>PO Number</label><input id="fPO" class="input"/></div><div class="field"><label>Container</label><input id="fContainer" class="input"/></div><div class="field"><label>Vendor</label><input id="fVendor" class="input"/></div><div class="field"><label>Status</label><select id="fStatus" class="input"><option value="">All</option><option>Draft</option><option>In Progress</option><option>Ready for Verification</option><option>Verified</option><option>Completed</option></select></div><div class="field"><label>From</label><input id="fFrom" type="date" class="input"/></div><div class="field"><label>To</label><input id="fTo" type="date" class="input"/></div><div class="field"><label>User</label><input id="fUser" class="input"/></div><div class="field actions-end"><button type="button" class="btn primary" onclick="UCH.load()">Search</button><button type="button" class="btn" onclick="UCH.clearFilters()">Clear</button></div></section>
<section class="card grid-card"><div class="grid-head"><div><h2>Receiving Records</h2><p id="historyCount">Loading&hellip;</p></div></div><div class="table-wrap"><table><thead><tr><th>PO</th><th>Vendor</th><th>Container</th><th>Unload Date</th><th>Unload By</th><th>Status</th><th>Items</th><th>Mismatches</th><th>Last Updated</th><th></th></tr></thead><tbody id="historyBody"></tbody></table></div></section>
<div id="toast" class="toast hidden"></div>
</asp:Content>
<asp:Content ID="s" ContentPlaceHolderID="ScriptContent" runat="server"><script src="Scripts/history.js?v=1.3.1"></script></asp:Content>
